apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "500Mi"
        memory: "500Mi"
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
