apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "200Mi"
        memory: "200Mi"
      requests:
        cpu:    "100Mi"
        memory: "100Mi"
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
