apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "200m"
      requests:
        memory: "100m"
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
